### ISSUE TITLE
Increase Width of side bar

### ISSUE THREAD

**Issue by RohitRam9701** [khzg/ChatGPT#5]
![2024-06-22 (1)](https://github.com/khzg/ChatGPT/assets/89768042/bc9f12e9-d3fe-48ad-a7df-3c8eea0a30bc)
**Cannot resize after some point, it takes 2 unit width of total width of 6.5 unit of my screen, make it resizable upto 3.5 - 4 unit width of any normal 16:9 ratio screen**

**Comment by khzg** [comment]
This is related to the browser limitations, it is not bigger than this.
